[general]
#import = ["~/.config/alacritty/catppuccin/catppuccin-latte.toml"]
#import = ["~/.config/alacritty/catppuccin/catppuccin-frappe.toml"]
#import = ["~/.config/alacritty/catppuccin/catppuccin-macchiato.toml"]
#import = ["~/.config/alacritty/catppuccin/catppuccin-mocha.toml"]
import = ["~/.config/alacritty/my-mocha.toml"]


[window]
dynamic_padding = true
padding = { x = 5, y = 5 }

[font]
size = 12

[font.normal]
family = "Inconsolata"
style = "Regular"

[cursor.style]
shape = "Beam"
blinking = "Always"